[package]
name = "learn_axum_jwt_api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
axum-extra = { version = "0.9.3", features = ["typed-header"] }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
jsonwebtoken = "9"
tower-http = { version = "0.5", features = ["auth"] }
chrono = "0.4.44"
