[package]
name = "MongoDB-Rust-tutorial"
version = "0.1.0"
edition = "2024"

[dependencies]
serde =  { version = "1.0.188", features = ["derive"] }
futures = "0.3.28"
tokio = {version = "1.32.0", features = ["full"]}
axum = { version = "0.7", features = ["ws"] }
serde_json = "1.0"
tower = "0.4"
tower-http = { version = "0.5", features = ["cors", "trace"] }
tracing = "0.1"
tracing-subscriber = "0.3"

[dependencies.mongodb]
version = "3.6.0"
